#logging:
#  level:
#    root: INFO
#    org:
#      springframework:
#        boot:
#          autoconfigure:
#            DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/movie-postgres
    username: movie-postgres
    password: movie-postgres
